package model;
// Generated Mar 8, 2016 11:00:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String correo;
     private String contrasenia;
     private int idpais;

    public Usuario() {
    }

    public Usuario(int id, String nombre, String correo, String contrasenia, int idpais) {
       this.id = id;
       this.nombre = nombre;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.idpais = idpais;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=64)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="correo", nullable=false, length=128)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="contrasenia", nullable=false, length=128)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    
    @Column(name="idpais", nullable=false)
    public int getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(int idpais) {
        this.idpais = idpais;
    }




}


